import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// ¡CLAVE! Asegúrate que la ruta del CSS de Bootstrap esté correcta
import "bootstrap/dist/css/bootstrap.min.css";
// Renombramos la importación a NavBar para que coincida con el nombre del componente.
import NavBar from "./components/Nav-Bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Aquí renderizamos la NavBar UNA SOLA VEZ, aplicable a todas las páginas */}
        <NavBar />

        {/* {children} es el contenido de app/page.tsx y otras rutas */}
        {children}
      </body>
    </html>
  );
}
